import { spawn } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../../..");

// The same catalog.json the Go CLI embeds at build time (go:generate ./gen).
// Reading the generated file directly rather than shelling out to `wp-ops
// list --json` buys two things: command_search works even when the Go binary
// hasn't been built, and it gets the full manifest — args, flags, examples,
// platform — where `list --json` deliberately exposes only a frozen subset
// (see printJSON's comment in go/cmd/list.go, which calls that output a stable
// contract for external tooling). Regenerated by `go generate ./internal/catalog/`.
const CATALOG_PATH = path.join(REPO_ROOT, "go/internal/catalog/catalog.json");

const paramSchema = z
  .object({
    name: z.string(),
    required: z.boolean().optional(),
    choices: z.array(z.string()).optional(),
    default: z.string().optional(),
    description: z.string().optional(),
  })
  .passthrough();

const entrySchema = z
  .object({
    category: z.string(),
    key: z.string(),
    description: z.string(),
    script_path: z.string(),
    runs_on: z.string().optional(),
    requires: z.array(z.string()).optional(),
    doc: z.string().optional(),
    args: z.array(paramSchema).optional(),
    flags: z.array(paramSchema).optional(),
    examples: z.array(z.string()).optional(),
    platform: z.string().optional(),
    display_category: z.string().optional(),
  })
  .passthrough();

export type CatalogEntry = z.infer<typeof entrySchema>;

let cached: CatalogEntry[] | undefined;

export function loadCatalog(): CatalogEntry[] {
  if (cached) return cached;

  if (!existsSync(CATALOG_PATH)) {
    throw new Error(
      `Command catalog not found at ${CATALOG_PATH}. It is generated from the scripts' ` +
        `manifest headers — run \`go generate ./internal/catalog/\` from the repo's go/ directory.`
    );
  }

  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(CATALOG_PATH, "utf-8"));
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Command catalog at ${CATALOG_PATH} is not valid JSON: ${message}`);
  }

  const result = z.array(entrySchema).safeParse(raw);
  if (!result.success) {
    throw new Error(`Command catalog at ${CATALOG_PATH} has an unexpected shape: ${result.error.message}`);
  }

  cached = result.data;
  warnOnAllowlistDrift(cached);
  return cached;
}

// Commands that only read — audits, scans, log analysis, traffic stats. These
// run without confirm; everything else in the catalog needs an explicit
// confirm: true.
//
// This gate is a speed bump, not a security boundary: the model can always set
// confirm itself. Its real job is to make anything that writes, deploys, or
// deletes surface to the user as a distinct decision instead of disappearing
// into a chain of tool calls.
//
// Hardcoded here because the manifest has no "does this mutate anything"
// directive yet. The data-driven version is an @mutates field alongside @runs
// and @platform, parsed in go/internal/manifest and carried through
// catalog.json — at which case this set goes away and the gate reads the entry.
// Until then warnOnAllowlistDrift catches keys that get renamed out from under it.
const READ_ONLY_COMMANDS = new Set([
  "scripts/git/gh-traffic",
  "scripts/git/git-log-oneline",
  "scripts/images/openverse_search",
  "scripts/misc/post-count",
  "scripts/monitoring/404-checker",
  "scripts/monitoring/ai-bot-monitor",
  "scripts/monitoring/error-monitor",
  "scripts/monitoring/monitor",
  "scripts/monitoring/redirect-check",
  "scripts/monitoring/remote-ttfb-ua",
  "scripts/monitoring/security-monitor",
  "scripts/monitoring/server-monitor",
  "scripts/monitoring/traffic-by-country",
  "scripts/monitoring/traffic-monitor",
  "scripts/monitoring/ttfb-test",
  "trellis/monitoring/quick-status",
  "trellis/monitoring/security-scan",
  "trellis/monitoring/traffic-report",
  "trellis/security/check-deny-ips",
  "trellis/security/check-ips",
  "wp-cli/diagnostics/diagnostic-transients",
  "wp-cli/diagnostics/list-posts-count",
  "wp-cli/security/scanner-general",
  "wp-cli/security/scanner-targeted",
  "wp-cli/security/scanner-wrapper",
  "wp-cli/seo/blog-audit",
  "wp-cli/seo/orphan-links-audit",
  "wp-cli/seo/orphan-pages-audit",
  "wp-cli/seo/page-audit",
  "wp-cli/seo/redirect-audit",
  "wp-cli/seo/schema-audit",
]);

// A renamed or deleted script would silently drop off the allowlist and start
// demanding confirmation for something read-only — annoying, and easy to
// misread as "this command is dangerous". stderr is safe here: stdio transport
// reserves stdout for the JSON-RPC stream, but stderr is free.
function warnOnAllowlistDrift(entries: CatalogEntry[]): void {
  const keys = new Set(entries.map((e) => e.key));
  const stale = [...READ_ONLY_COMMANDS].filter((k) => !keys.has(k));
  if (stale.length > 0) {
    console.error(
      `wp-ops MCP: READ_ONLY_COMMANDS lists ${stale.length} command(s) not in the catalog ` +
        `(renamed or removed?): ${stale.join(", ")}`
    );
  }
}

// Introspection flags never reach the underlying script — go/cmd/dispatch.go's
// executeEntry handles --where and --help before any executor runs — so they
// are always safe regardless of what the command itself does.
const INTROSPECTION_FLAGS = new Set(["--help", "-h", "--where"]);

export function isIntrospectionOnly(args: string[]): boolean {
  return args.length > 0 && INTROSPECTION_FLAGS.has(args[0]);
}

export function isReadOnlyCommand(key: string): boolean {
  return READ_ONLY_COMMANDS.has(key);
}

// Mirrors catalog.Search in go/internal/catalog/catalog.go: case-insensitive
// substring over key and description, sorted by key. Kept deliberately
// identical so `wp-ops search X` and command_search(X) can't disagree about
// what exists.
export function searchCatalog(
  entries: CatalogEntry[],
  query: string,
  opts: { platform?: string; category?: string } = {}
): CatalogEntry[] {
  const term = query.toLowerCase();
  return entries
    .filter((e) => {
      if (opts.platform && e.platform !== opts.platform) return false;
      if (opts.category && e.display_category !== opts.category && e.category !== opts.category) return false;
      return e.key.toLowerCase().includes(term) || e.description.toLowerCase().includes(term);
    })
    .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
}

// Resolves an entry the way the CLI does: exact key first, then a unique
// basename. Ambiguity is reported rather than guessed at — same policy as
// go/cmd/dispatch.go's printAmbiguous.
export function resolveCommand(entries: CatalogEntry[], name: string): CatalogEntry {
  const exact = entries.find((e) => e.key === name);
  if (exact) return exact;

  const base = (key: string) => key.slice(key.lastIndexOf("/") + 1);
  const matches = entries.filter((e) => base(e.key) === name);

  if (matches.length === 1) return matches[0];
  if (matches.length > 1) {
    throw new Error(
      `"${name}" matches more than one command: ${matches.map((m) => m.key).join(", ")}. ` +
        `Use the full key.`
    );
  }
  throw new Error(`Unknown command "${name}". Use command_search to find the right key.`);
}

function formatParams(label: string, params: CatalogEntry["args"]): string[] {
  if (!params || params.length === 0) return [];
  const lines = [`${label}:`];
  for (const p of params) {
    const bits: string[] = [p.required ? "required" : "optional"];
    if (p.choices && p.choices.length > 0) bits.push(`one of: ${p.choices.join(" | ")}`);
    else if (p.default) bits.push(`default/example: ${p.default}`);
    lines.push(`  ${p.name}  (${bits.join(", ")})${p.description ? ` — ${p.description}` : ""}`);
  }
  return lines;
}

export function formatEntryDetail(e: CatalogEntry): string {
  const lines = [
    `${e.key}`,
    `  ${e.description}`,
    "",
    `script:   ${e.script_path}`,
    `platform: ${e.platform ?? "any"}   runs on: ${e.runs_on ?? "local"}`,
  ];
  if (e.requires && e.requires.length > 0) lines.push(`requires: ${e.requires.join(", ")}`);
  lines.push(
    `write gate: ${isReadOnlyCommand(e.key) ? "read-only — runs without confirm" : "requires confirm: true"}`
  );
  lines.push("");
  lines.push(...formatParams("arguments", e.args));
  lines.push(...formatParams("flags", e.flags));
  if (e.examples && e.examples.length > 0) {
    lines.push("examples:");
    for (const ex of e.examples) lines.push(`  ${ex}`);
  }
  if (e.doc) lines.push("", `docs: ${e.doc}`);
  return lines.join("\n").replace(/\n{3,}/g, "\n\n");
}

export function formatSearchResults(matches: CatalogEntry[], query: string): string {
  if (matches.length === 0) {
    return `No commands match "${query}". Try a broader term, or search with no filters to list everything.`;
  }

  // One hit is almost always the command the caller wanted, and the follow-up
  // is always "how do I call it" — so answer that in the same round trip.
  if (matches.length === 1) {
    return `1 match for "${query}":\n\n${formatEntryDetail(matches[0])}`;
  }

  const rows = matches.map((e) => {
    const tags = [e.platform ?? "any"];
    if (e.runs_on === "server") tags.push("server");
    if (!isReadOnlyCommand(e.key)) tags.push("needs confirm");
    return `  ${e.key.padEnd(48)} [${tags.join(", ")}] ${e.description}`;
  });

  return (
    `${matches.length} matches for "${query}":\n\n${rows.join("\n")}\n\n` +
    `Call command_run with a key and ["--help"] for full usage of any of these.`
  );
}

// wp-ops resolution, widest-applicability first: an explicit override, then the
// binary built in this checkout, then whatever is installed on PATH.
function resolveWpOpsBin(): string {
  if (process.env.WP_OPS_BIN) return process.env.WP_OPS_BIN;
  const local = path.join(REPO_ROOT, "go/wp-ops");
  if (existsSync(local)) return local;
  return "wp-ops";
}

export interface RunResult {
  stdout: string;
  stderr: string;
  code: number;
  timedOut: boolean;
}

export function runCatalogCommand(key: string, args: string[], timeoutMs: number): Promise<RunResult> {
  return new Promise((resolve, reject) => {
    const bin = resolveWpOpsBin();
    // Dispatched by full key, never by basename: the short form can go
    // ambiguous the moment a second script shares a basename, and that would
    // turn a previously-working call into an error at the worst moment.
    const child = spawn(bin, [key, ...args], { cwd: REPO_ROOT });

    let stdout = "";
    let stderr = "";
    let timedOut = false;

    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGTERM");
      // SIGTERM is enough for a shell script but not for something wedged in
      // an uninterruptible read; escalate rather than hang the MCP call.
      setTimeout(() => child.kill("SIGKILL"), 5_000).unref();
    }, timeoutMs);

    child.stdout.on("data", (d) => (stdout += d));
    child.stderr.on("data", (d) => (stderr += d));
    child.on("error", (err) => {
      clearTimeout(timer);
      const message = (err as NodeJS.ErrnoException).code === "ENOENT"
        ? `wp-ops binary not found at "${bin}". Build it with \`go build -o go/wp-ops ./go\`, ` +
          `install it on PATH, or set WP_OPS_BIN.`
        : err.message;
      reject(new Error(message));
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ stdout, stderr, code: code ?? 1, timedOut });
    });
  });
}

const MAX_OUTPUT_CHARS = 40_000;

export function formatRunResult(key: string, result: RunResult, timeoutMs: number): string {
  const parts: string[] = [];
  if (result.stdout.trim()) parts.push(result.stdout.trim());
  if (result.stderr.trim()) parts.push(`STDERR:\n${result.stderr.trim()}`);

  let body = parts.join("\n\n") || "(no output)";
  if (body.length > MAX_OUTPUT_CHARS) {
    // Keep the tail: these are scripts, and the summary/verdict is at the end.
    body =
      `[truncated — showing the last ${MAX_OUTPUT_CHARS} of ${body.length} characters]\n\n` +
      body.slice(-MAX_OUTPUT_CHARS);
  }

  if (result.timedOut) {
    return `${key} timed out after ${timeoutMs}ms and was killed. Partial output:\n\n${body}`;
  }
  if (result.code !== 0) {
    return `${key} exited with code ${result.code}.\n\n${body}`;
  }
  return body;
}
